### ISSUE TITLE
"chapter1 have no attribute named 'horde mode'. "

### ISSUE THREAD

**Issue by StaticSploit** [JordanLeich/Dead-End#59]
I am trying to playing this game. But when a check point comes, game asks me do you want to continue when I say yes it is being like the photo I will attach. 
![Ekran Alıntısı](https://github.com/JordanLeich/Dead-End/assets/95934071/747c0813-d91b-4bd5-9a4b-68c8ea0191c9)

**Comment by JordanLeich** [comment]
@StaticSploit I see you closed this issue, did you manage to figure out what was wrong?

**Comment by StaticSploit** [comment]
I have opened the issue page wrong, sorry. In the last version of the game
it was already fixed. Sorry About that

Jordan Leich ***@***.***>, 24 Ağu 2023 Per, 02:59 tarihinde
şunu yazdı:
